// Configuration settings for the current test
// This file is generated by vscode on build - DO NOT EDIT

#pragma once

#define LOCAL_TEST
#define TEST_FUNC permuteUnique

#include <vector>
#include <string>
using std::vector;

using test_return_type = vector<vector<int>>;
using test_arg_type = vector<int>;
const std::string test_name = "permuteUnique";
