// Configuration settings for the current test
// This file is generated by vscode on build - DO NOT EDIT

#pragma once

#define LOCAL_TEST
#define TEST_FUNC removeElement

#include <string>
#include <tuple>

using std::tuple;
using std::vector;

using test_return_type = int;

using test_args_types = tuple<vector<int>&,int>;

struct TestCase {
	test_args_types args;
	test_return_type expected;
};

const std::string test_name = "removeElement";